sudo: required
services:
  - docker


before_install:
  - docker build -t eshwarmk/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true eshwarmk/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-336187774577"
  bucket_path: "docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY